name: 定时运行 JavaScript 文件

on:
  schedule:
    - cron: '0 22 * * *'  # 每天午夜 12 点执行 (可以根据需要修改时间)
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  run-js:
    runs-on: ubuntu-latest  # 选择操作系统环境

    steps:
      - name: Checkout 代码
        uses: actions/checkout@v2  # 获取代码

      - name: 设置 Node.js 环境
        uses: actions/setup-node@v3  # 设置 Node.js 环境
        with:
          node-version: '18'  # 可以根据需要修改 Node.js 版本

      - name: 设置 pnpm 环境
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: 安装依赖
        run: pnpm install

      - name: 打包
        run: pnpm build

      - name: 运行 JavaScript 文件
        run: node dist/cron.js  # 用 node 命令运行你的 JS 文件
