name: 测试上传

on:
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  run-js:
    runs-on: ubuntu-latest  # 选择操作系统环境
    permissions:
      id-token: write  # 允许 GitHub Actions 写入身份令牌
      contents: read   # 允许访问仓库内容

    steps:
      - name: Checkout 代码
        uses: actions/checkout@v2  # 获取代码

      - name: Set up Google Cloud authentication 
        uses: google-github-actions/auth@v1
        with:
          create_credentials_file: true  # 生成凭证文件
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: 'psyched-summer-450303-h3'

      - name: 'Set up gcloud'
        uses: google-github-actions/setup-gcloud@v1
      
      - name: 设置 Node.js 环境
        uses: actions/setup-node@v3  # 设置 Node.js 环境
        with:
          node-version: '18'  # 可以根据需要修改 Node.js 版本

      - name: 设置 pnpm 环境
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: 安装依赖
        run: pnpm install

      - name: 打包
        run: pnpm build

      - name: 运行 JavaScript 文件
        run: node dist/test.js  # 用 node 命令运行你的 JS 文件
